#!/usr/bin/env bash

CONFIGDIR="${HOME}/.config/webxecute"
CONFIGFILE="${CONFIGDIR}/config"

if  [ ! -d $CONFIGDIR ] || [ ! -f $CONFIGFILE ]; then
    while true; do
    read -p  "You do not have any config file. Do you want to generate the default one? [y/n]." yn
    case $yn in
        [Yy]* )
            if [ ! -d $CONFIGDIG ]; then
                mkdir $CONFIGDIR;
            fi
            touch $CONFIGFILE
            echo "# Syntax is 'name|url'" >> $CONFIGFILE
            echo "# Syntax for parameterized url is url/{}/{}" >> $CONFIGFILE
            echo "" >> $CONFIGFILE
            echo "github|https://www.github.com" >> $CONFIGFILE
            echo "github/user/repo|https://www.github.com/{}/{}" >> $CONFIGFILE
            echo "Config file generated: ${CONFIGFILE}"
            exit;;
        [Nn]* ) exit;;
        * ) exit;;
    esac
    done
fi

# for some reason newlines are trimmed if not using a file in shell scripts?!
TEMPFILE="/tmp/webxecute_sanitized" 
TEMPSORTEDFILE="/tmp/webxecute_sorted"

# skip # comments and empty lines
cat $CONFIGFILE | grep -vE "^#" | grep . > $TEMPFILE
SANITIZED=`cat $TEMPFILE`

if [[ -f $TEMPSORTEDFILE ]]; then
    rm $TEMPSORTEDFILE
fi

touch $TEMPSORTEDFILE

# sort by favorites first, with the leading * removed
cat $TEMPFILE | grep -E "^\*" | cut -c 2- >> $TEMPSORTEDFILE
cat $TEMPFILE | grep -vE "^\*" >> $TEMPSORTEDFILE
SANITIZED=`cat $TEMPSORTEDFILE`
SELECTED=`echo "$SANITIZED" | cut -d "|" -f1 | fzf`

if [[ -z $SELECTED ]]; then
    exit 0
fi

RED='\033[0;31m'
RESET='\033[0m'
COLOREDCURLY=`printf "${RED}{}${RESET}"`
URL=`echo "$SANITIZED" | grep -m 1 "^${SELECTED}|" | cut -d "|" -f2`

while [[ $URL == *"{}"* ]]; do
    # color the first matching {} in red and ask for parameter input.
    COLOREDURL=`echo "$URL" | sed "0,/{}/s|{}|$COLOREDCURLY|"`
    echo -e "$COLOREDURL" 
    read -p "parameter: " PARAM

    # replace first occurence of '{}' with $PARAM
    SEDEXPR="0,/{}/s|{}|$PARAM|"
    URL=`echo "$URL" | sed "$SEDEXPR"`
done

xdg-open $URL 2>&1 > /dev/null &
