#!/usr/bin/env bash

SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
CONFIGFILE=${SCRIPTPATH}/endpoints

# skip # comments and empty lines
TEMPFILE="/tmp/webxecute_sanitized" # for some reason newlines are trimmed if not using a file in shell scripts?!
SANITIZED=`cat $CONFIGFILE | grep -vE "^#" | grep . > $TEMPFILE`
SELECTED=`cat $TEMPFILE | cut -d "|" -f1 | fzf`

if [[ -z $SELECTED ]]; then
    exit 0
fi

URL=`cat $CONFIGFILE | grep $SELECTED | cut -d "|" -f2`

xdg-open $URL 2>&1 > /dev/null &
